[package]
name = "ffs"
version = "0.1.0"
edition = "2021"
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/TheLazyDutchman/ffs/"
keywords = ["parsing"]
description = "An easy way to create your own parsers"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parse-macro-derive = "0.1.0"
rand = "0.8.0"
