[package]
name = "ffs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parse-macro-derive = {path = "parse-macro-derive"}
rand = "0.8.0"