[package]
name = "ffs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pass_macro_attribute = { path = "pass_macro_attribute" }

[target.debug]
rustflags = [
  "-C", "link-arg=-Tlayout.ld",
  "-C", "link-arg=-nostartfiles",
  "-C", "prefer-dynamic"
]